import Footer from '@/app/components/Footer'
import HeroSection from '@/app/components/HeroSection'
import Navbar from '@/app/components/Navbar'
import { Description } from '@radix-ui/react-dialog'
import React from 'react'
import CityHeroSection from '../alabama/components/CityHeroSection'


const cities = [
    "Anniston",
    "Auburn",
    "Birmingham",
    "Dothan",
    "Florence",
    "Hoover",
    "Huntsville",
    "Mobile",
    "Montgomery",
    "Tuscaloosa",
    "Adamsville",
    "Alabaster",
    "Albertville",
    "Alexander City",
    "Alexandria",
    "Andalusia",
    "Arab",
    "Argo",
    "Athens",
    "Atmore",
    "Attalla",
    "Bay Minette",
    "Bessemer",
    "Boaz",
    "Brent",
    "Brewton",
    "Brook Highland",
    "Calera",
    "Center Point",
    "Centre",
    "Chelsea",
    "Chickasaw",
    "Childersburg",
    "Citronelle",
    "Clanton",
    "Clay",
    "Cottondale",
    "Cullman",
    "Dadeville",
    "Daleville",
    "Daphne",
    "Decatur",
    "Demopolis",
    "Elba",
    "Emerald Mountain",
    "Enterprise",
    "Eufaula",
    "Fairfield",
    "Fairhope",
    "Fayette",
    "Foley",
    "Forestdale",
    "Fort Payne",
    "Fort Rucker",
    "Fultondale",
    "Gadsden",
    "Gardendale",
    "Glencoe",
    "Grand Bay",
    "Grayson Valley",
    "Greenville",
    "Gulf Shores",
    "Guntersville",
    "Haleyville",
    "Hamilton",
    "Hanceville",
    "Hartselle",
    "Harvest",
    "Hazel Green",
    "Headland",
    "Heflin",
    "Helena",
    "Highland Lakes",
    "Hokes Bluff",
    "Holt",
    "Holtville",
    "Homewood",
    "Hueytown",
    "Irondale",
    "Jackson",
    "Jacksonville",
    "Jasper",
    "Kimberly",
    "Kinsey",
    "Lake View",
    "Lanett",
    "Leeds",
    "Lincoln",
    "Livingston",
    "Madison",
    "Margaret",
    "Marion",
    "Meadowbrook",
    "Meridianville",
    "Midfield",
    "Millbrook",
    "Monroeville",
    "Montevallo",
    "Moody",
    "Moores Mill",
    "Moulton",
    "Moundville",
    "Mount Olive",
    "Mountain Brook",
    "Muscle Shoals",
    "Northport",
    "Odenville",
    "Oneonta",
    "Opelika",
    "Opp",
    "Orange Beach",
    "Oxford",
    "Ozark",
    "Pelham",
    "Pell City",
    "Phenix City",
    "Piedmont",
    "Pike Road",
    "Pine Level",
    "Pinson",
    "Pleasant Grove",
    "Prattville",
    "Priceville",
    "Prichard",
    "Rainbow City",
    "Rainsville",
    "Red Bay",
    "Redland",
    "Roanoke",
    "Robertsdale",
    "Russellville",
    "Saks",
    "Saraland",
    "Satsuma",
    "Scottsboro",
    "Selma",
    "Semmes",
    "Sheffield",
    "Smiths Station",
    "Southside",
    "Spanish Fort",
    "Sumiton",
    "Sylacauga",
    "Talladega",
    "Tallassee",
    "Tarrant",
    "Theodore",
    "Thomasville",
    "Tillmans Corner",
    "Troy",
    "Trussville",
    "Tuscumbia",
    "Tuskegee",
    "Underwood-Petersville",
    "Union Springs",
    "Valley",
    "Valley Grande",
    "Vestavia Hills",
    "Warrior",
    "Weaver",
    "West End-Cobb Town",
    "Wetumpka",
    "Winfield",
    "Woodstock",
]

// ****** Temporary demo page ********
const descriptoin = "We provide home appliance repair and HVAC system services throughout all of the top cities in Alabama! Whether you're looking for expert appliance repair, need to have your HVAC system fixed, or simply scheduling a maintenance call, Sears Home Services has expert technicians in your city."
function page() {
    return (
        <div>
            <Navbar />
            <CityHeroSection cities={cities} description={descriptoin} />
            <Footer />
        </div>
    )
}

export default page
